# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb64a6f6bf145ba0c27af1df7c45cd54dacc9ca65fcd2a2604d1bfc1e41d642a2d930218a8c710095db90f3ed485ef8cc7d836a81cf4384963a719c132953d4d

test:
  secret_key_base: 5e5ea39430584c10f8cd143684e799189e8ca20c7f5cc08d12c7f3c08757232396a923edfad3c6b47a1e58198eca0c575ba3882b49400481e8af6ea5cdfc2464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
